#10838 Added support to use script from PCW
datasaur-ai/robosaur pull request #14
Opened 2022-03-21 09:02 UTC by daniel-jeremia

## Changes
* Added `pcwPayloadSource` and `pcwPayload` to Config interface
* Added `PCWTransformer` and its mapper files
* Updated `README.md`

## How to test
To use the script generated from PCW use the option `--use-pcw` on `create-projects` command.

```bash
npm run start -- create-projects <path-to-config-file> --use-pcw
```

When using `--use-pcw` option, provide both `pcwPayloadSource` and `pcwPayload` inside `project` in the config file.

For further instructions, see `README.md`

2022-03-22 08:30 UTC, daniel-jeremia commented
@tonoman3g what do you think about the codegen? If possible, it's better to use prod, but I don't think the endpoint is opened. And its also risking exposing the queries and mutations to public

2022-03-23 03:32 UTC, jonathancesario commented on package.json
> +}
enter

2022-03-23 04:01 UTC, tonoman3g commented
btw, 

our backend supports document assignment with email and team_member_id...

@daniel-jeremia

2022-03-23 04:02 UTC, tonoman3g commented
> @tonoman3g what do you think about the codegen? If possible, it's better to use prod, but I don't think the endpoint is opened. And its also risking exposing the queries and mutations to public

for now lets use localhost first, then let's reassess whether we should expose the introspection api in prod or not @daniel-jeremia

2022-03-23 04:06 UTC, daniel-jeremia commented
> our backend supports document assignment with email and team_member_id...
@tonoman3g I see, got it, I'll try it




> for now lets use localhost first, then let's reassess whether we should expose the introspection api in prod or not

@tonoman3g okay, all good :))

2022-03-23 04:11 UTC, tonoman3g commented on src/config/interfaces.ts
> +  INLINE = 'inline',
what do you mean by Storage INLINE? @daniel-jeremia

2022-03-23 04:11 UTC, tonoman3g commented on src/transformer/pcw-transformer/helper/doc-file-options.mapper.ts
> +  fromPcw: (payload: DocFileOptionsInput): Config['project']['docFileOptions'] => {
please create the unit test for these mappers

2022-03-23 04:11 UTC, tonoman3g commented on src/transformer/pcw-transformer/pcw.transformer.ts
> +    throw new Error('usePcw is true but pcwPayloadSource is not provided, please provide pcwPayloadSource');
create an error class and reuse that error, so there won't be many duplication here

2022-03-23 04:14 UTC, daniel-jeremia commented on src/config/interfaces.ts
> +  INLINE = 'inline',
INLINE meaning the script from PCW is directly copy and pasted in the config.json inside the "pcwPayload" key @tonoman3g

2022-03-23 04:39 UTC, ivanm-gdp commented
@daniel-jeremia 
I tried using `--use-pcw`, and cmiiw, but it is intended that Robosaur will **_ignore_** `documents` and `documentAssignments` ya?

I see that you already mentioned `documentAssignments` in first post, and for documents is also understandable since Robosaur's goal is to automate multiple project creation. Just thought that we might want to mention this somewhere in the readme 👍🏼 

---

Oh, and could you maybe provide a sample config.json with pcw payload pasted in?
we can use existing token-based payload, but with the project config stripped out

this is what I used, for reference
[config.token.pcw.txt](https://github.com/datasaur-ai/robosaur/files/8329730/config.token.pcw.txt)

2022-03-23 04:44 UTC, ivanm-gdp commented
> >our backend supports document assignment with email and team_member_id...
>
> I see, got it, I'll try it


I think for Robosaur to support using `team_member_id` directly, the [validation logic](https://github.com/datasaur-ai/robosaur/blob/f/%2310838/src/assignment/validate-assignments.ts) needs to be updated slightly
also, I believe we already have a query to get members of the team and we can add teamMemberId there 
https://github.com/datasaur-ai/robosaur/blob/bb9dde77e19062cd0d4fd33c6f34874f8b649753/src/datasaur/get-team-members.ts#L4-L22

2022-03-23 04:50 UTC, jonathancesario reviewed
and also, can you list the things that aren't working and have to go with a different approach like assignment?

2022-03-23 04:50 UTC, jonathancesario commented on src/handlers/create-projects.handler.ts
> +      if (updatedProjectConfig.labelSets) break;
what's the use case for this?

2022-03-23 04:50 UTC, jonathancesario commented on src/index.ts
> +  .option('--use-pcw', 'Whether to use the script shown during Project Creation Wizard in Datasaur UI', false)
Whether to use the payload from Project Creation Wizard in Datasaur UI

2022-03-23 04:50 UTC, jonathancesario commented on src/transformer/pcw-transformer/helper/doc-file-options.mapper.ts
> +      firstRowAsHeader: payload.firstRowAsHeader!,
why so many use of `!`?

2022-03-23 04:50 UTC, jonathancesario commented on src/transformer/pcw-transformer/helper/label-set.mapper.ts
> +      return {
could be simplified, no need to use `return`

2022-03-23 04:50 UTC, jonathancesario commented on src/transformer/pcw-transformer/helper/doc-file-options.mapper.ts
> +    return {
could be simplified, no need to use return

2022-03-23 04:50 UTC, jonathancesario commented on src/transformer/pcw-transformer/helper/doc-file-options.mapper.ts
> +  fromPcw: (payload: DocFileOptionsInput): Config['project']['docFileOptions'] => {
can we use Config.project.docFileOptions instead? much safer typings, please apply to all

2022-03-23 04:57 UTC, daniel-jeremia commented
> Robosaur will **_ignore_** `documents` and `documentAssignments` ya?

Yes, for documents and documentAssignments (currently) Robosaur will use config outside of PCW. As for labelSets and questionSets. Robosaur will **prioritize** config inside PCW payload, if it doesn't exist then it will find from the config.json

2022-03-23 04:58 UTC, daniel-jeremia commented
> Just thought that we might want to mention this somewhere in the readme

Got it. As for documentAssignments, I'm still trying so that it will also prioritize config in pcwPayload

2022-03-23 04:59 UTC, daniel-jeremia commented
> Oh, and could you maybe provide a sample config.json with pcw payload pasted in?

Got it, i have the quickstart but decided not to push it. Will do.

2022-03-23 05:00 UTC, daniel-jeremia commented
> I believe we already have a query to get members of the team and we can add teamMemberId there

I'll try to use team_member_id directly and modify the validation first, if it is difficult, I'll try querying the email using this. Thank you

2022-03-23 05:00 UTC, daniel-jeremia commented
> and also, can you list the things that aren't working and have to go with a different approach like assignment?

got it. @jonathancesario

2022-03-23 05:04 UTC, daniel-jeremia commented on readme.md
> +### Using Script from PCW
oh okay, I was just thinking some people might not understand the word payload

2022-03-23 05:04 UTC, daniel-jeremia commented on readme.md
> +       "gcs": { "gcsCredentialJson": "config/google-cloud-storage/credential.json" }
I'll fix it

2022-03-23 05:06 UTC, daniel-jeremia commented on src/handlers/create-projects.handler.ts
> +      if (updatedProjectConfig.labelSets) break;
To prioritize label set from pcwPayload. Without that `break`, the labelset config will be overwritten by the labelset given in config.json (outside pcwPayload)

2022-03-23 05:07 UTC, daniel-jeremia commented on src/transformer/pcw-transformer/helper/doc-file-options.mapper.ts
> +      firstRowAsHeader: payload.firstRowAsHeader!,
Because from the graphql.ts it uses InputMaybe, so all of the attribute is optional. Is there a better way to do this? @jonathancesario

2022-03-23 06:24 UTC, daniel-jeremia commented on src/transformer/pcw-transformer/helper/doc-file-options.mapper.ts
> +  fromPcw: (payload: DocFileOptionsInput): Config['project']['docFileOptions'] => {
this seemed to give error
`Cannot access 'Config.project' because 'Config' is a type, but not a namespace. Did you mean to retrieve the type of the property 'project' in 'Config' with 'Config["project"]'?`

2022-03-23 07:03 UTC, ivanm-gdp commented on src/transformer/pcw-transformer/helper/doc-file-options.mapper.ts
> +  fromPcw: (payload: DocFileOptionsInput): Config['project']['docFileOptions'] => {
oh ya
I dunno why, but typescript allows us to access 'inner' types via brackets, but not dot notation

2022-03-24 06:06 UTC, daniel-jeremia commented on src/config/interfaces.ts
> +  INLINE = 'inline',
That's true, should I separate it from StorageSource? Maybe I can do like
`pcwPayloadSource: StorageSource | 'INLINE'`

Yes, S3 and GCP is supported.

2022-03-27 17:40 UTC, jonathancesario requested changes

2022-03-27 17:40 UTC, jonathancesario commented on src/assignment/assign-auto-documents.ts
> +  const labelerIdentifier: string[] = [];
identifiers?

2022-03-27 17:40 UTC, jonathancesario commented on src/assignment/assign-auto-documents.ts
> +  const reviewerIdentifier: string[] = [];
ditto

2022-03-27 17:40 UTC, jonathancesario commented on src/assignment/interfaces.ts
> +   * @description whether to use team_member_id or not. Defaults to false (use email)
can you explain a bit further? i don't think that this one is self explanatory like labelers and reviewers

2022-03-27 17:40 UTC, jonathancesario commented on src/assignment/interfaces.ts
> +  use_team_member_id?: boolean;
and don't we use camel case for variable name?

2022-03-27 17:40 UTC, jonathancesario commented on src/transformer/pcw-transformer/error/pcw-payload-not-provided.error.ts
> +    super('usePcw is true but pcwPayload or pcwPayloadSource is not provided, please provide the required options');
are not provided

2022-03-27 17:40 UTC, jonathancesario commented on src/transformer/pcw-transformer/helper/doc-file-options.mapper.ts
> +    firstRowAsHeader: payload.firstRowAsHeader!,
is `!` really needed?

2022-03-27 17:40 UTC, jonathancesario commented on src/transformer/pcw-transformer/pcw.transformer.ts
> +export const pcwTransformer = async (input: Config) => {
this is way too long
- rename it to verb
- extract the validation
- make helper function for each specific transformation
wdyt?

2022-03-28 02:22 UTC, daniel-jeremia commented on src/assignment/assign-auto-documents.ts
> +  const labelerIdentifier: string[] = [];
because it can use email OR teamMemberId, so I changed the variable name to Identifier

2022-03-28 02:22 UTC, daniel-jeremia commented on src/assignment/assign-auto-documents.ts
> +  const reviewerIdentifier: string[] = [];
idem

2022-03-28 02:22 UTC, daniel-jeremia commented on src/assignment/interfaces.ts
> +  use_team_member_id?: boolean;
oh right, i"ll change it

2022-03-28 02:23 UTC, daniel-jeremia commented on src/assignment/interfaces.ts
> +   * @description whether to use team_member_id or not. Defaults to false (use email)
`whether the labelers and reviewers contain email or teamMemberId` -> wdyt?

2022-03-28 02:23 UTC, daniel-jeremia commented on src/transformer/pcw-transformer/pcw.transformer.ts
> +export const pcwTransformer = async (input: Config) => {
yea you're probably right, will change it

2022-03-28 02:25 UTC, daniel-jeremia commented on src/transformer/pcw-transformer/helper/doc-file-options.mapper.ts
> +    firstRowAsHeader: payload.firstRowAsHeader!,
I think i'll just change the input type to not use InputMaybe

2022-03-28 11:25 UTC, jonathancesario commented on src/transformer/pcw-transformer/helper/doc-file-options.mapper.ts
> +      firstRowAsHeader: payload.firstRowAsHeader!,
then make the attribute also optional? for example, make `firstRowAsHeader` as optional too

2022-03-28 11:27 UTC, jonathancesario commented on src/transformer/pcw-transformer/helper/doc-file-options.mapper.ts
> +  fromPcw: (payload: DocFileOptionsInput): Config['project']['docFileOptions'] => {
ow my bad then but you can actually make the interface smaller and you can refer it to a specific part of the interface, e.g. the return of this function would be `ConfigDocFileOption[]`

2022-03-29 07:19 UTC, ivanm-gdp reviewed
Should the export folder contains the zipfile / JSON file of the export result?
This was on me - I accidentally commited some of them back in #7 😮‍💨 

It might be useful - users will know what structure to expect from the export config, but it also bloats the repo 🤔 
any suggestion what our approach should be?

2022-04-04 02:17 UTC, daniel-jeremia commented
@jonathancesario @darwin-gautalius @ivanm-gdp is this safe to merge?

2022-04-04 02:39 UTC, ivanm-gdp commented on src/assignment/assign-auto-documents.ts
> +  const labelerIdentifier: string[] = [];
I think what kak Rio meant here is to use `labelerIdentifiers` since it's an array 🤔

2022-04-04 02:55 UTC, ivanm-gdp commented
> @jonathancesario @darwin-gautalius @ivanm-gdp is this safe to merge?

From me, other than https://github.com/datasaur-ai/robosaur/pull/14#pullrequestreview-924138751 my concern about bloating the repo size due to export results, PR looks 👍🏼
Maybe kak Rio or kak Darwin have some thoughts on this?

Re-reading kak Rio's review, https://github.com/datasaur-ai/robosaur/pull/14#discussion_r835938502 seems to be about using plurals for arrays and not about identifier vs email

2022-04-04 03:19 UTC, daniel-jeremia commented
> Re-reading kak Rio's review, [#14 (comment)](https://github.com/datasaur-ai/robosaur/pull/14#discussion_r835938502) seems to be about using plurals for arrays and not about identifier vs email

ahhh i see xD

2022-04-04 04:18 UTC, jonathancesario commented on readme.md
> +  ...
this should be stated first, and then follow up by explaining how to replace the unsupported attributes

2022-04-04 04:19 UTC, jonathancesario commented on src/assignment/assign-auto-documents.ts
> +  const labelerIdentifier: string[] = [];
yes lino that's exactly it

2022-04-05 02:09 UTC, daniel-jeremia commented on readme.md
> +  ...
@jonathancesario what do you mean kak?

2022-04-07 06:29 UTC, daniel-jeremia commented
> my concern about bloating the repo size due to export results

@ivanm-gdp maybe this can be another issue xD

2022-04-07 07:01 UTC, jonathancesario commented
i think it's fine if we want to give an export example, just make sure it will be small in terms of size

2022-04-08 18:35 UTC, jonathancesario approved these changes

2022-04-11 02:32 UTC, merged