#11243 Moved documents and asssignments to project option
datasaur-ai/robosaur pull request #17
Opened 2022-04-05 03:55 UTC by daniel-jeremia

* Moved `documents` and `asssignments` to `project` option
* Updated Readme.md

2022-04-08 18:37 UTC, jonathancesario commented on quickstart/doc-based/config/config.json
> +    "documents": {
files?

2022-04-08 18:37 UTC, jonathancesario commented on quickstart/token-based/config/config.json
> +    "host": "http://localhost:8080",
revert this :sweat_smile:

2022-04-12 08:28 UTC, jonathancesario requested changes
i've updated the task so please also handle the rename of `project` to `create` because it introduce breaking changes, might as well handle all the things so we release it as a new version

2022-04-12 08:28 UTC, jonathancesario commented on quickstart/token-based/config/config.json
> +    "teamId": "1",
revert

2022-04-12 08:28 UTC, jonathancesario commented on quickstart/token-based/config/config.json
> +    "teamId": "1",
ditto

2022-04-12 09:37 UTC, daniel-jeremia commented
> i've updated the task so please also handle the rename of `project` to `create` because it introduce breaking changes, might as well handle all the things so we release it as a new version

Oke kak 👍 @jonathancesario

2022-04-19 18:20 UTC, jonathancesario requested changes
also needs to be updated
- `robosaur.md`
- `readme.md`

2022-04-20 18:51 UTC, jonathancesario requested changes

2022-04-20 18:51 UTC, jonathancesario commented on readme.md
> +Robosaur will try to create a project for each folder inside the `project.files.path` folder.
create.files.path?

2022-04-20 18:51 UTC, jonathancesario commented on readme.md
> +      Where our project folders are located. A bit different from `projectState.path`, `project.files.path` should be a folder path - relative or full.
ditto

2022-04-20 18:51 UTC, jonathancesario commented on readme.md
> +      Where our assignment file is located. `project.assignment.path` is similar to `projectState.path`, it should be a full or relative path pointing to a JSON file.
create.assignment.path?

2022-04-21 04:01 UTC, daniel-jeremia commented on readme.md
> +Robosaur will try to create a project for each folder inside the `project.files.path` folder.
eh.. iya ya udah ganti `create` xD

2022-04-21 06:56 UTC, jonathancesario approved these changes

2022-04-21 06:56 UTC, merged