f/#11265-kontext added support for processing zip files
datasaur-ai/robosaur pull request #19
Opened 2022-04-11 05:39 UTC by daniel-jeremia

2022-04-11 06:03 UTC, ivanm-gdp reviewed
for the parts using `mkdirSync`
do we need to use the recursive option?

case: 
we are at `root`, and we want to create `root/step1/step2`
when `root/step1` does not exist, I believe `fs.mkdirSync` will fail without the recursive option.

can this scenario happen?

--- 

haven't tried running Robosaur yet, will update my review again later

2022-04-11 09:40 UTC, daniel-jeremia commented
> can this scenario happen?

yes it can and will fail, I think this is intended. How will the app handle triple nesting e.g. Client1/Project1/SubProject1?
What project will be created? @ivanm-gdp

2022-04-11 10:07 UTC, ivanm-gdp commented
> > can this scenario happen?
> 
> yes it can and will fail, I think this is intended. How will the app handle triple nesting e.g. Client1/Project1/SubProject1? What project will be created? @ivanm-gdp

Oh, I see
the folder path is tied directly to the project name -> hence it's actually not possible to have nested directories in that way ya
ok then, no need to add `recursive` I believe 👍🏼

2022-04-11 19:25 UTC, jonathancesario requested changes
- i don't know about the `upload` directory, how about `input`? not ambiguous

2022-04-11 19:25 UTC, jonathancesario commented on src/config/interfaces.ts
> +   * @description Local file path where the folder containing zip files are located
a bit more explanation that indicates this one will be the project creation input

2022-04-11 19:25 UTC, jonathancesario commented on src/config/interfaces.ts
> +   * @description Local folder path to store extract result for the zip files. Leave it empty to use the zipRootPath
if it's empty, both the input and output (export result) will be on the same directory? isn't that odd?

2022-04-11 19:25 UTC, jonathancesario commented on src/config/interfaces.ts
> +   * @description Path to a folder in the cloud storage to store the extract results
i kinda lost, what's the difference between this one and `stagingFolderPath`?

2022-04-11 19:25 UTC, jonathancesario commented on src/config/interfaces.ts
> +   * @description Name of the folder inside the zip file containing the Images. Leave it empty if its the root folder.
images, not capital
is this needed? why not just use the path?

2022-04-11 19:25 UTC, jonathancesario commented on src/utils/kontext/handleFromZip.ts
> +export const handleFromZip = async (documentConfig: DocumentsConfig) => {
how about more specific? i think you can say `prepareCsvFromZip` or something like that? the current name is too general, i don't get a slightest hint about the "handle" process

2022-04-12 00:10 UTC, daniel-jeremia commented on src/config/interfaces.ts
> +   * @description Local file path where the folder containing zip files are located
got it

2022-04-12 00:10 UTC, daniel-jeremia commented on src/config/interfaces.ts
> +   * @description Local folder path to store extract result for the zip files. Leave it empty to use the zipRootPath
hmm yea i think that would be kinda odd, i'll make it not optional

2022-04-12 00:11 UTC, daniel-jeremia commented on src/config/interfaces.ts
> +   * @description Path to a folder in the cloud storage to store the extract results
`stagingFolderPath` is for specifying where to *extract* the zip files. `uploadPath` is the url to put the images in the cloud. @jonathancesario

2022-04-12 00:12 UTC, daniel-jeremia commented on src/config/interfaces.ts
> +   * @description Name of the folder inside the zip file containing the Images. Leave it empty if its the root folder.
This is to handle cases where there are more folders inside the extracted zip file. For example, in the sample zip file you gave me, the images are inside a folder called `Image`

2022-04-12 00:13 UTC, daniel-jeremia commented on src/utils/kontext/handleFromZip.ts
> +export const handleFromZip = async (documentConfig: DocumentsConfig) => {
got it

2022-04-12 04:38 UTC, jonathancesario commented
and also, we will need a readme because it will be used by non-engineers people

2022-04-12 04:43 UTC, daniel-jeremia commented on src/utils/kontext/handleFromZip.ts
> +  clearDirectory(documentConfig.path);
i decided to change how the staging works, so this shouldn't be an issue anymore

2022-04-12 06:26 UTC, ivanm-gdp commented on src/utils/kontext/deleteAllFilesFromDirectory.ts
> +  });
this time it's the documents' directory 🤔 

![image](https://user-images.githubusercontent.com/89899945/162894262-9d157b4e-b590-4dad-83da-3d093fedf8f3.png)


I tried creating both the staging & documents dir, but got a different error
![image](https://user-images.githubusercontent.com/89899945/162894343-be4dcf46-cc86-4b6d-b5b5-38d649ec74e4.png)


in general, I think Robosaur need to handle all the cases
- folder exist -> don't fail on `mkdir`
- folder does not exist -> don't fail on `rmdir`

2022-04-12 09:42 UTC, daniel-jeremia commented on src/utils/kontext/deleteAllFilesFromDirectory.ts
> +  });
> folder exist -> don't fail on mkdir
> folder does not exist -> don't fail on rmdir

I see, okay i'll keep that in mind. Fyi staging folder is not used anymore. I changed it to temp and user doesn't need to know about it. @ivanm-gdp

2022-04-13 04:38 UTC, jonathancesario commented on quickstart/kontext/readme.md
> +3. After that, those extracted images will be uploaded to the chosen cloud object storage while still in the same original folder structure even the cloud. While uploading, Robosaur will save the url
... folder structure, even the cloud -- add a comma
`document.path`

2022-04-13 04:38 UTC, jonathancesario commented on quickstart/kontext/readme.md
> +   - `containingFolder`, use this option if the images inside the zip file is contained in another folder. Note that the folder structure inside all zip files should be the same. e.g.
the name should be adjusted?

2022-04-13 04:38 UTC, jonathancesario commented on src/utils/kontext/deleteAllFilesFromDirectory.ts
> +    if (response === 'N' || response === 'n') {
is it safer to check with the yes condition? since it will be mutable

2022-04-13 04:38 UTC, jonathancesario commented on src/utils/kontext/errors/folderDoesntExists.ts
> +export class FolderDoesntExist extends Error {
a bit odd to use don't/doesn't for this -- grammar concern
how about just `FolderNotExist`? or better yet, `FolderNotFound`? a default error message for this condition

2022-04-13 04:38 UTC, jonathancesario commented on src/utils/kontext/prepareCsvFromZip.ts
> +  const stagingFolderPath = resolve(zipRootPath, TEMP_FOLDER_NAME);
tempFolderPath?

2022-04-13 06:27 UTC, jonathancesario approved these changes

2022-04-13 07:18 UTC, merged