#11349 [Robosaur] Update project creation to use PCW as the default approach
datasaur-ai/robosaur pull request #20
Opened 2022-04-18 05:47 UTC by daniel-jeremia

2022-04-21 11:00 UTC, jonathancesario requested changes
all previous changes regarding naming some attributes gets replaced

2022-04-21 11:00 UTC, jonathancesario commented on src/datasaur/utils/get-extensions.ts
> +  let LABELER: ExtensionID[] = [];
simplify with reduce and you can return directly

2022-04-22 02:02 UTC, daniel-jeremia commented on src/assignment/parse-assignment.spec.ts
> +  xit.each([
no, i meant to skip the test because I actually didn't use parseAssignment with the current implementation

2022-04-22 02:02 UTC, daniel-jeremia commented on src/config/interfaces.ts
> +  project: CreateConfig;
that is still required kak

2022-04-22 02:02 UTC, daniel-jeremia commented on src/config/schema/validator.ts
> +    if (source) {
got it

2022-04-22 02:03 UTC, daniel-jeremia commented on src/datasaur/create-project.ts
> +        : EXTENSIONS[settings.documentSettings.kind || 'TOKEN_BASED'].LABELER,
because documnetSettings.kind is now optional, since its deprecated, so I need to give default value or throw error

2022-04-22 02:03 UTC, daniel-jeremia commented on src/datasaur/utils/get-extensions.ts
> +  let LABELER: ExtensionID[] = [];
i did try with reduce, it's a little complicated, but i'll try again xD

2022-04-22 11:19 UTC, jonathancesario reviewed
if I use option `--use-pcw` does it still work?

2022-04-22 11:29 UTC, daniel-jeremia commented
> if I use option `--use-pcw` does it still work?

right, sorry i forgot xD
it will work now

2022-04-22 13:14 UTC, jonathancesario commented on src/config/interfaces.ts
> +   * @description Required if --use-pcw is used
all this description should be changed to
`Required if no options is provided or --use-pcw is used`

2022-04-25 04:03 UTC, jonathancesario requested changes

2022-04-25 04:03 UTC, jonathancesario commented on src/transformer/pcw-transformer/interfaces.ts
> +   * @description Required if --use-pcw is used
miss this one

2022-04-25 04:09 UTC, daniel-jeremia commented on src/transformer/pcw-transformer/interfaces.ts
> +   * @description Required if --use-pcw is used
@jonathancesario right, my bad, pushed again

2022-04-25 04:19 UTC, jonathancesario approved these changes

2022-04-25 04:19 UTC, merged