#11914 Replace all customScriptId to fileTransformerId
datasaur-ai/robosaur pull request #29
Opened 2022-05-25 09:02 UTC by michael-jong-ds

1. replaced customScriptId to fileTransformerId
2. adjusted documentation and descriptions to support the change

2022-05-28 04:53 UTC, daniel-jeremia approved these changes

2022-05-29 18:03 UTC, jonathancesario requested changes
- there are still some config on quickstart that contains `customScriptId`
- there is one link that not working anymore on robosaur.md, replace the last path with `/file-transformer`

2022-05-29 18:03 UTC, jonathancesario commented on sample/storage/google-cloud-storage/config.json
> +      "fileTransformerId": "<FILE TRANSFORMER ID>",
also tidy up this format? either choose `FILE_TRANSFORMER_ID` or `FILE TRANSFORMER ID` for all placeholder on config

2022-05-30 02:51 UTC, jonathancesario approved these changes

2022-05-30 03:06 UTC, merged