#11979 Add tag filter for export project
datasaur-ai/robosaur pull request #30
Opened 2022-05-30 01:43 UTC by robbydrmwn

2022-05-30 02:36 UTC, tonoman3g commented on src/config/interfaces.ts
> +    tags?: string[];
please add the ajv validation too, i think there is a validation with ajv library for the config file

2022-05-30 02:36 UTC, tonoman3g commented on src/handlers/export-projects.handler.ts
> +    throw new Error(`${tagsName} is not found.`);
is tagsName will be printed as array here? @robbydrmwn

2022-05-30 04:03 UTC, robbydrmwn commented on src/handlers/export-projects.handler.ts
> +    throw new Error(`${tagsName} is not found.`);
`PASSED,REWORKSS is not found.` will be like this. Separated comma.

Aku baru kepikiran satu case, kalo multiple tags, misal projectFilter.tags : ['A', 'B']. Kalo tim tersebut gak punya tags 'B', harusnya di throw error juga ya? @tonoman3g

2022-05-30 04:09 UTC, robbydrmwn commented on src/handlers/export-projects.handler.ts
> +    throw new Error(`${tagsName} is not found.`);
>   const tagIds = tagsName.map((tagName) => {
>     const tag = tags.find((tag) => tag.name === tagName);
>     if (tag === undefined) {
>       throw new Error(`${tagName} is not found.`);
>     }
>     return tag.id;
>   });

kalo satu aja gak ketemu, mau di throw, berarti jadi kayak gini

2022-05-30 04:11 UTC, robbydrmwn commented
gw baru realize, tags di BE skrg sifatnya `OR`, apa berarti perlu adjust BE untuk tambahin filter baru ya @tonoman3g

2022-05-30 04:24 UTC, tonoman3g commented on src/handlers/export-projects.handler.ts
> +    throw new Error(`${tagsName} is not found.`);
dithrow aja gpp @robbydrmwn

2022-05-30 04:25 UTC, tonoman3g commented
> gw baru realize, tags di BE skrg sifatnya `OR`, apa berarti perlu adjust BE untuk tambahin filter baru ya @tonoman3g

nabila waktu itu uda aware sih kalau sifatnya OR.

coba bahas di slack deh @robbydrmwn buat confirmation

2022-05-30 05:01 UTC, michael-jong-ds approved these changes
LGTM

2022-05-30 08:51 UTC, robbydrmwn commented
> > gw baru realize, tags di BE skrg sifatnya `OR`, apa berarti perlu adjust BE untuk tambahin filter baru ya @tonoman3g
> 
> nabila waktu itu uda aware sih kalau sifatnya OR.
> 
> coba bahas di slack deh @robbydrmwn buat confirmation

okay, confirmed bener `OR`

2022-05-31 01:05 UTC, tonoman3g commented on src/config/schema/export-schema-validator.ts
> +    projectFilter: { type: 'object', nullable: true, required: ['kind'] },
oh kind itu required ya? 

kita bisa ngevalidate kalau tags harus array of string jg gak?

2022-05-31 01:05 UTC, tonoman3g commented on src/config/schema/export-schema-validator.ts
> +import Ajv, { JSONSchemaType } from 'ajv';
oh ya, ada readme atau documentation yg harus diupdate kah? cc @jonathancesario

2022-05-31 02:23 UTC, robbydrmwn commented on src/config/schema/export-schema-validator.ts
> +    projectFilter: { type: 'object', nullable: true, required: ['kind'] },
dari interface nya iya, kalo ada projectFilter, kind nya required
make sure aja deh, ini intended kan? @daniel-jeremia 

> kita bisa ngevalidate kalau tags harus array of string jg gak?
updated @tonoman3g

2022-06-02 03:25 UTC, tonoman3g approved these changes

2022-06-02 03:34 UTC, jonathancesario commented on src/config/schema/export-schema-validator.ts
> +import Ajv, { JSONSchemaType } from 'ajv';
yes on readme root and gitbook

2022-06-02 03:35 UTC, jonathancesario requested changes
please add example on quickstart directory

2022-06-02 09:16 UTC, jonathancesario commented
@robbydrmwn sure as long as there is an example
@daniel-jeremia wdyt? what's the best use case to use quickstart or sample?

2022-06-02 10:26 UTC, daniel-jeremia commented
> @robbydrmwn sure as long as there is an example
> @daniel-jeremia wdyt? what's the best use case to use quickstart or sample?

I think quickstart is used more as a start point for the user, so the user can just edit from there. While sample is like a more advanced example of how to use a specific feature. 

I think in this case sample might be the better option

2022-06-02 10:27 UTC, daniel-jeremia commented on src/config/schema/export-schema-validator.ts
> +    projectFilter: { type: 'object', nullable: true, required: ['kind'] },
Yes, kind is required soalnya different kinds differrnt supported export format. 

Sorry i just saw this github notification

2022-06-03 01:08 UTC, robbydrmwn commented
> i kinda lean towards quickstart since this is an additional filter on export, which already exist on all of the quickstart example all you have to do is adding this new attribute to each one of them

updated @jonathancesario

2022-06-03 03:21 UTC, jonathancesario approved these changes
don't forget to update GitBook

2022-06-04 03:03 UTC, daniel-jeremia approved these changes

2022-06-06 02:25 UTC, merged