#11980 Add command to mark projects as in review
datasaur-ai/robosaur pull request #31
Opened 2022-06-02 02:51 UTC by ivanm-gdp

## Changes
- add `@types/lodash` as devDependencies
- new handler: `src/handlers/revert-completed-projects.handler.ts`
  - adjust config schema to support this payload
- new graphql payload: `src/datasaur/toggle-cabinet-status.ts`

## TODO
- [ ] need to change the base branch - 
- [ ] need input on the logic checking project current status before sending toggle request

2022-06-02 03:05 UTC, tonoman3g commented on readme.md
> +The file `data.txt` should be a newline-separated file containing one projectId per line. The projectId itself can be obtained from the URL when we open a project in the Datasaur web app, specificall
can you put data.txt example?

2022-06-02 03:05 UTC, tonoman3g commented on readme.md
> +    "source": "gcs",
please give the example to read the data.txt from local file, not from the gcs

2022-06-02 03:05 UTC, tonoman3g commented on src/handlers/revert-completed-projects.handler.ts
> +  getLogger().info(`Project with COMPLETED status: ${validProjectIds}`);
please print the number of completed / valid projects

2022-06-02 03:05 UTC, tonoman3g commented on src/handlers/revert-completed-projects.handler.ts
> +  const projectIds = await getProjectIds(getConfig().revert);
please print the number of project id provided in csv file

2022-06-02 03:12 UTC, ivanm-gdp commented on readme.md
> +$ npm run start -- revert-completed-projects-to-in-review -h
yes, as with the other command examples 
this part shows the help of the command

2022-06-02 03:14 UTC, ivanm-gdp commented on readme.md
> +The file `data.txt` should be a newline-separated file containing one projectId per line. The projectId itself can be obtained from the URL when we open a project in the Datasaur web app, specificall
🤔  the `projectId`s in the example file will not be valid. Is that okay?

2022-06-02 03:40 UTC, ivanm-gdp commented on src/handlers/revert-completed-projects.handler.ts
> +  const projectIds = await getProjectIds(getConfig().revert);
we decided to simplify the input a bit - instead of a CSV file it would be a txt file instead

2022-06-02 03:49 UTC, ivanm-gdp commented
ohh 
since the PR is no longer against master, the unit test are not running ya 😆

2022-06-02 04:19 UTC, tonoman3g commented on readme.md
> +    "source": "gcs",
@ivanm-gdp just wondering, why for apply-tags, we put the csv file in the command, but for this, we put the data.txt in the config.json

? 

e.g.

```
npm run start -- apply-tags <configFile> <csvFile> <teamId>

```

2022-06-02 04:46 UTC, ivanm-gdp commented on readme.md
> +    "source": "gcs",
full discussion in Slack yaa

2022-06-02 07:09 UTC, tonoman3g commented on src/handlers/revert-completed-projects.handler.ts
> +  const projectIds = await getProjectIds(getConfig().revert);
noted

2022-06-02 07:09 UTC, tonoman3g commented
> ohh since the PR is no longer against master, the unit test are not running ya 😆

ah this is because of the github action ya

2022-06-02 07:10 UTC, tonoman3g commented on readme.md
> +The file `data.txt` should be a newline-separated file containing one projectId per line. The projectId itself can be obtained from the URL when we open a project in the Datasaur web app, specificall
yes, it is okay, as long as we put the example.
@ivanm-gdp

2022-06-02 10:16 UTC, ivanm-gdp commented on readme.md
> +The file `data.txt` should be a newline-separated file containing one projectId per line. The projectId itself can be obtained from the URL when we open a project in the Datasaur web app, specificall
I have added two configs and data.txt under quickstart
I mentioned them in readme.md with links to the actual file too

[here](https://github.com/datasaur-ai/robosaur/blob/f/%2311980-revert-in-review/readme.md#revert-completed-projects-to-in-review)

I put them in quickstart since its similar to the others:
- after editing team_id & datasaur credentials, we can run the command with no errors
but because the projectIds are invalid, there will be no change in the user's workspace

this will be the output of running the command: 
```
{"level":"info","message":"reading config from: quickstart/revert/config.json","timestamp":"2022-06-02 17:16:29"}
{"level":"info","message":"Found 5 projectIds in quickstart/revert/data.txt","timestamp":"2022-06-02 17:16:29"}
{"level":"info","message":"generating access token...","timestamp":"2022-06-02 17:16:29"}
{"level":"info","message":"finished generating access token...","timestamp":"2022-06-02 17:16:29"}
{"count":0,"level":"info","message":"Project with COMPLETED status: ","projects":[],"timestamp":"2022-06-02 17:16:29"}
{"count":5,"level":"warn","message":"Project with other status: sample12345,projectId67,UPPERCASE89,lowercase01,numeric2345","projects":["sample12345","projectId67","UPPERCASE89","lowercase01","numeric2345"],"timestamp":"2022-06-02 17:16:29"}
{"level":"warn","message":"Robosaur will only process projects with COMPLETE status","timestamp":"2022-06-02 17:16:29"}
{"level":"info","message":"No valid projects are found.","timestamp":"2022-06-02 17:16:29"}
```

@tonoman3g

2022-06-02 18:50 UTC, jonathancesario requested changes

2022-06-02 18:50 UTC, jonathancesario commented on quickstart/revert/config.inline.json
> +    "payload": ["sample12345", "projectId67", "UPPERCASE89", "lowercase01", "numeric2345"],
why not using JSON as the format? so that inline and file could have the same value

2022-06-03 03:00 UTC, ivanm-gdp commented on quickstart/revert/config.inline.json
> +    "payload": ["sample12345", "projectId67", "UPPERCASE89", "lowercase01", "numeric2345"],
from the flow in the [docs](https://docs.google.com/document/d/1W4NQWqr82e1TfyZmmTKGXHJBc751augN4gcegyY-EIk/edit#heading=h.mxhzdqo466zy)

the flow will be something like: 
1. use 'export-project-list` from #32 to get CSV of projects
2. select a % of them to be QA-ed
3. mark project pass / fail manually
4. failed projects -> used as input for this command

 I think it's more user friendly to create a txt file of projectIds 
```
id1
id2
id3
```
compared to having to create a JSON array manually
```json
[
  "id1", 
  "id2", 
  "id3"
]
```
wdyt kak @jonathancesario ?

2022-06-03 03:22 UTC, jonathancesario commented on quickstart/revert/config.inline.json
> +    "payload": ["sample12345", "projectId67", "UPPERCASE89", "lowercase01", "numeric2345"],
if they're not asking explicitly for that format, i think JSON is still acceptable since it's more universal and consistent throughout robosaur

2022-06-03 03:38 UTC, ivanm-gdp commented on quickstart/revert/config.inline.json
> +    "payload": ["sample12345", "projectId67", "UPPERCASE89", "lowercase01", "numeric2345"],
noted, will update to support JSONs instead!

2022-06-03 04:00 UTC, ivanm-gdp commented on readme.md
> +The file `data.txt` should be a newline-separated file containing one projectId per line. The projectId itself can be obtained from the URL when we open a project in the Datasaur web app, specificall
outdated, per https://github.com/datasaur-ai/robosaur/pull/31#discussion_r888279100

put inside `sample` folder instead

2022-06-03 07:54 UTC, jonathancesario approved these changes

2022-06-06 01:28 UTC, ivanm-gdp commented on src/handlers/revert-completed-projects.handler.ts
> +  const validProjectIds = validProject.map((p) => p.id);
@jonathancesario @tonoman3g 
would like a final confirmation

since we need to check each project's current status (COMPLETE or not)
is this flow okay? 

the current implementation is fetching all COMPLETE projects under a team, and then checking it vs the input

I think currently Datasaur GQL don't have a `getProjects(ids)` query yet, so the alternative to this approach would be to send a separate `getProject(id)` query for each entry in the input - which I think can trigger a 429 too many request quite quickly

But the `getProjects(filter)` would also query & retrieves all COMPLETE projects, and if a team has tons of them, might also lead to a slow processing time...

2022-06-06 01:47 UTC, tonoman3g commented on src/handlers/revert-completed-projects.handler.ts
> +  const validProjectIds = validProject.map((p) => p.id);
i think function getProjects should be called per iteration, we should not collect all the projects in a big array then iterate the array.

we should process the projects by always querying it.
```
let projects = await getProjects() // take 100 project at one time
while (projects.length > 0) {
    ....
}
```

@ivanm-gdp

2022-06-06 03:56 UTC, ivanm-gdp commented
rebased & force-pushed

2022-06-06 04:29 UTC, ivanm-gdp commented on src/handlers/revert-completed-projects.handler.ts
> +import { chunk } from 'lodash';
@tonoman3g  
updated flow using manual paginated quesry

🤔  we still have to check all first -> then send all the revert request
I believe if we send the revert status request while checking, the project count changes, and can cause undesired behavior in the skip-take pagination

2022-06-06 07:47 UTC, ivanm-gdp commented on src/handlers/revert-completed-projects.handler.ts
> +  while (i < inputProjectIds.length) {
at first I tried being a bit smart - chunk the projectId to smaller amount (I tried 5), and using await Promise.all
but that caused robosaur to request multiple tokens 🤔 
and that triggers 429 way more often

```
{"level":"info","message":"Retrieving details for id0",...}
{"level":"info","message":"generating access token...",...}
{"level":"info","message":"Retrieving details for id1",...}
{"level":"info","message":"generating access token...",...}
{"level":"info","message":"Retrieving details for id2",...}
{"level":"info","message":"generating access token...",...}
{"level":"info","message":"Retrieving details for id3",...}
{"level":"info","message":"generating access token...",...}
{"level":"info","message":"Retrieving details for id4",...}
{"level":"info","message":"generating access token...",...}
```

so in the end I stick with regular while loop

2022-06-06 07:55 UTC, tonoman3g commented on src/handlers/revert-completed-projects.handler.ts
> +  while (i < inputProjectIds.length) {
ahaha sip2. its okay @ivanm-gdp

2022-06-06 10:12 UTC, merged