#11981 Add a command to tag projects
datasaur-ai/robosaur pull request #33
Opened 2022-06-03 09:47 UTC by michael-jong-ds

1. Added command to tag projects
2. The payload for tags can be in the form of csv, or inline
3. If the tag is not found, it will be created in the team

Any feedback is appreciated, thanks!

2022-06-04 03:20 UTC, daniel-jeremia commented on src/datasaur/create-tag.ts
> +import { query } from "./query";
what is this import for?

2022-06-04 03:26 UTC, daniel-jeremia commented on src/handlers/constants.ts
> +  APPLY_TAGS = 'APPLY TAGS',
Don't use space

2022-06-04 03:27 UTC, daniel-jeremia commented on src/handlers/apply-tags.handler.ts
> +      return config.payload;
make some error handling for when the storage source is X, then Y have to be provided, otherwise throw error

2022-06-04 03:27 UTC, daniel-jeremia commented on src/handlers/apply-tags.handler.ts
> +    case StorageSources.LOCAL:
might as well support other storage sources (?)

2022-06-04 03:27 UTC, daniel-jeremia commented on src/index.ts
> +program
please also update readme.md and git book. thanks :)

2022-06-04 03:33 UTC, daniel-jeremia commented on src/handlers/apply-tags.handler.ts
> +    const tagList = await getTeamTags(config.teamId)
duplicate? should just use `teamTagsList` above

2022-06-04 03:38 UTC, daniel-jeremia commented on src/handlers/apply-tags.handler.ts
> +      project.tags.push(tagList.find((tagItem)=>tagItem.name === tag))
1. why need to use `find`? u made sure that the tags are created with `createNoneExistingTags` function right?

2. forgot spaces

2022-06-04 03:39 UTC, daniel-jeremia commented on src/handlers/apply-tags.handler.ts
> +  createNonexistingTags(tagsToApplyList,teamTagsNames,config)
typo, e in  `existing` should be capitalized

2022-06-04 03:41 UTC, daniel-jeremia commented on src/handlers/apply-tags.handler.ts
> +      project.tags.push(tagList.find((tagItem)=>tagItem.name === tag))
oh nvm, u need to get the ID ya

2022-06-04 03:41 UTC, daniel-jeremia commented on src/handlers/apply-tags.handler.ts
> +    const tagIds = await project.tags.map((tag)=>{
forgot spaces

2022-06-04 03:42 UTC, daniel-jeremia commented on src/handlers/apply-tags.handler.ts
> +    updateProjectTag((await project).projectId, (await project).tags)
hmm, why need await?

2022-06-04 03:43 UTC, daniel-jeremia commented on src/index.ts
> +program
also make a sample config file in sample folder

2022-06-04 04:44 UTC, jonathancesario requested changes
lots of formatting error, maybe you forgot to setup the auto-save formatter?

2022-06-04 04:44 UTC, jonathancesario commented on src/config/schema/apply-tags-schema-validator.ts
> +export const applyTagsSchemaValidator = schemaValidator.compile(ApplyTagsSchema);
enter

2022-06-04 04:44 UTC, jonathancesario commented on src/datasaur/create-tag.ts
> +}
enter

2022-06-04 04:44 UTC, jonathancesario commented on src/handlers/apply-tags.handler.ts
> +import { updateProjectTag } from "../datasaur/update-project-tag";
sort all import alphabetically based on its path

2022-06-04 04:44 UTC, jonathancesario commented on src/handlers/apply-tags.handler.ts
> +  setConfigByJSONFile(configFile, getApplyTagValidators(), ScriptAction.APPLY_TAGS)
lots of missing `;` on this file

2022-06-04 04:44 UTC, jonathancesario commented on src/handlers/apply-tags.handler.ts
> +  createNonexistingTags(tagsToApplyList,teamTagsNames,config)
createNonExistingTags

2022-06-04 04:44 UTC, jonathancesario commented on src/handlers/apply-tags.handler.ts
> +    const project = await getProject(payload.projectId)
i think it's better to use `getProjects` first so that you don't have to request for each loop

2022-06-04 04:44 UTC, jonathancesario commented on src/handlers/apply-tags.handler.ts
> +}
enter

2022-06-04 04:44 UTC, jonathancesario commented on src/handlers/apply-tags.handler.ts
> +  projects.forEach(async (project)=>{
hm this is a bit tricky, instead of something like this, you should make sure the previous loop is done
so after fetching all projects, make sure your loop is synchronized or let it run async but use Promise.allSettled to make sure all process is finished

2022-06-06 06:21 UTC, michael-jong-ds commented on src/handlers/constants.ts
> +  APPLY_TAGS = 'APPLY TAGS',
done

2022-06-06 06:21 UTC, michael-jong-ds commented on src/handlers/apply-tags.handler.ts
> +    case StorageSources.LOCAL:
added support for cloud storage

2022-06-06 06:21 UTC, michael-jong-ds commented on src/handlers/apply-tags.handler.ts
> +      return config.payload;
added support for cloud storage

2022-06-06 06:22 UTC, michael-jong-ds commented on src/handlers/apply-tags.handler.ts
> +  createNonexistingTags(tagsToApplyList,teamTagsNames,config)
whoops, my bad

2022-06-06 06:22 UTC, michael-jong-ds commented on src/handlers/apply-tags.handler.ts
> +    const tagIds = await project.tags.map((tag)=>{
whoops, my bad

2022-06-06 10:13 UTC, michael-jong-ds commented on src/index.ts
> +program
Added sample config

2022-06-06 10:23 UTC, jonathancesario requested changes

2022-06-06 10:23 UTC, jonathancesario commented on readme.md
> +<TAG_1>,<PROJECT_ID_1>
update tags example?

2022-06-06 10:23 UTC, jonathancesario commented on sample/apply-tags/tags.csv
> +<TAG_3>,<PROJECT_ID_2>
enter?

2022-06-06 10:23 UTC, jonathancesario commented on src/handlers/apply-tags.handler.ts
> +    if (projectTag.includes(',')) {
i don't think you need to add this conditional, you can just split it with `,` whether there is a comma or not

2022-06-06 10:33 UTC, michael-jong-ds commented on sample/apply-tags/tags.csv
> +<TAG_3>,<PROJECT_ID_2>
there shouldn't be an empty line at the bottom of the csv, it causes errors

2022-06-06 10:36 UTC, michael-jong-ds commented on src/handlers/apply-tags.handler.ts
> +    if (projectTag.includes(',')) {
I've removed it

2022-06-06 10:36 UTC, michael-jong-ds commented on readme.md
> +<TAG_1>,<PROJECT_ID_1>
whoops, my bad, forgot to update readme

2022-06-06 10:53 UTC, jonathancesario approved these changes

2022-06-06 10:54 UTC, merged