F/#13088 adjust pcw schema
datasaur-ai/robosaur pull request #45
Opened 2022-08-09 03:09 UTC by michael-jong-ds

**Merge into master after https://github.com/datasaur-ai/robosaur/pull/42**

1. Added version checker -> if version is greater or equal to 5.38.0, use new `projectSettings` with `conflictResolution`, otherwise, it will use the old version (with consensus directly in projectSettings)
2. Updated consensus validator to use new version by default

2022-08-09 03:23 UTC, michael-jong-ds commented
merge after https://github.com/datasaur-ai/robosaur/pull/42

2022-08-09 04:26 UTC, jonathancesario requested changes

2022-08-09 04:26 UTC, jonathancesario commented on src/transformer/pcw-transformer/helper/getDatasaurVersion.ts
> +import fetch from 'node-fetch';
sort alphabetically

2022-08-09 04:26 UTC, jonathancesario commented on src/transformer/pcw-transformer/setConfigFromPcw.ts
> +  getConfig().create.projectSettings = isVersionGreaterThanOrEqual(datasaurVersion, PROJECT_SETTINGS_BREAKING_VERSION)
instead of this, how about we make it more generic?
```
  enum DatasaurVersion {
    DEFAULT
    v5.38
  }
  Map<DatasaurVersion, (payload) => Config>
```
so if there is a new version that introduces breaking changes, we just add to that

2022-08-09 10:47 UTC, jonathancesario requested changes

2022-08-09 10:47 UTC, jonathancesario commented on src/transformer/pcw-transformer/constants.ts
> +  DEFAULT = 'latest',
might as well change to LATEST too?

2022-08-09 10:47 UTC, jonathancesario commented on src/transformer/pcw-transformer/setConfigFromPcw.ts
> +  const projectSettingsMapper = DatasaurVersionMapper.get(datasaurVersion)!;
rename the variable to `getProjectSettings`?

2022-08-09 10:47 UTC, jonathancesario commented on src/transformer/pcw-transformer/helper/getDatasaurVersion.ts
> +import fetch from 'node-fetch';
don't forget this one

2022-08-09 10:47 UTC, jonathancesario commented
@ivanm-gdp please review this which already includes your changes

2022-08-09 11:25 UTC, michael-jong-ds commented on src/transformer/pcw-transformer/helper/getDatasaurVersion.ts
> +import fetch from 'node-fetch';
Ini uda auto sorted di latest commit
harusnya uda ngikutin schema yg ada di file-file lain?

2022-08-09 12:52 UTC, ivanm-gdp commented on src/transformer/pcw-transformer/helper/getDatasaurVersion.ts
> +import fetch from 'node-fetch';
Ohh, maybe vscode a bit buggy ya because fetch is imported from node-fetch, and the other are relative imports. 

Usually we import node_modules things first up-top, then relative imports. 


nitpick - but can you change this to use axios? 
I believe the other requests in Robosaur currently use axios. node-fetch is there because it's a dependency for azure's package

2022-08-10 03:27 UTC, ivanm-gdp commented on src/transformer/pcw-transformer/helper/compareVersion.ts
> +  }
this for-loop
```ts
for (const i in v1List){
  ...
}
```

trus `i` nya dipake buat indexing? ngga salah nih?

2022-08-10 03:32 UTC, ivanm-gdp commented on src/transformer/pcw-transformer/helper/project-settings.mapper.ts
> +});
5.38+, support conflictResolution

5.37 and below, only support consensus. 

I think there is a logic error here 🤔 

![image](https://user-images.githubusercontent.com/89899945/183807117-84227026-7204-493b-ac8d-5635b09df6b6.png)

2022-08-10 03:48 UTC, ivanm-gdp commented on src/transformer/pcw-transformer/helper/compareVersion.ts
> +  }
ohhh, my bad ini for-in bukan for-of ya 🤦🏼

2022-08-10 03:52 UTC, ivanm-gdp commented on src/transformer/pcw-transformer/helper/project-settings.mapper.ts
> +});
Oh! ignore this
I was changing the wrong variables - I thought front-end-configuration got the version from `APP_VERSION`, but turns out it's from `FRONTEND_VERSION`

2022-08-10 04:00 UTC, ivanm-gdp approved these changes

2022-08-10 04:02 UTC, ivanm-gdp commented on src/transformer/pcw-transformer/helper/project-settings.mapper.ts
> +});
maybe we can use `/api/health` instead so the version is tied to backend's APP_VERSION, as opposed to frontend's FRONTEND_VERSION

2022-08-10 04:12 UTC, michael-jong-ds commented on src/transformer/pcw-transformer/helper/project-settings.mapper.ts
> +});
actually I found a logic error on the parse version, it will return just the first higher version, not the correct version. I'm currently fixing this
cc @ivanm-gdp

2022-08-10 07:21 UTC, ivanm-gdp commented on src/transformer/pcw-transformer/helper/compareVersion.ts
> +    if (value.localeCompare(version, undefined, { numeric: true }) != -1) {
![image](https://user-images.githubusercontent.com/89899945/183839384-d563ea40-d4e0-4a7c-9ce0-1d58bfc55288.png)

Ohh seems to suit our needs ya
MDN docs for future reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare#numeric_sorting

`!==` strict equality ya, just to be safe

2022-08-10 08:08 UTC, jonathancesario commented on src/transformer/pcw-transformer/constants.ts
> +  DEFAULT = 'LATEST',
change it to `LATEST` also?

2022-08-10 08:11 UTC, jonathancesario approved these changes

2022-08-10 08:11 UTC, merged