#13879 [Robosaur] Trigger ML assisted labeling when creating projects (PoC)
datasaur-ai/robosaur pull request #49
Opened 2022-10-13 09:39 UTC by michael-jong-ds

1. Added functions to trigger auto label (ML assisted labeling) on project creation

2022-10-17 07:48 UTC, jonathancesario requested changes
how about creating a new file, e.g. `auto-label.handler.ts`? move all the logic and the create-projects handler could just import it

2022-10-17 07:48 UTC, jonathancesario commented on src/config/interfaces.ts
> +  autoLabel: AutoLabelConfig;
doesn't have to be? could be undefined

2022-10-17 07:48 UTC, jonathancesario commented on src/config/interfaces.ts
> +  labelerEmail: string;
what is this for?

2022-10-17 07:48 UTC, jonathancesario commented on src/config/interfaces.ts
> +  numberOfFilesPerRequest: number;
is there any limitation for this attribute?

2022-10-17 07:48 UTC, jonathancesario commented on src/handlers/create-projects.handler.ts
> +  const filtered = new Map(
return right away?

2022-10-17 08:47 UTC, michael-jong-ds commented on src/config/interfaces.ts
> +  numberOfFilesPerRequest: number;
none that I know of, apa ada restriction dari api nya?

2022-10-18 18:58 UTC, jonathancesario approved these changes

2022-10-18 18:59 UTC, merged